import {chooseValue,selectObject,chooseExample,runCompute,researchApi} from './scientific-helpers';
import {session} from './session';
import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
test.use({baseURL:'http://127.0.0.1:8879'});

test('model-settings: late initial catalog cannot hide a just-saved profile',async({page})=>{
  let release=()=>{};const gate=new Promise<void>(resolve=>{release=resolve;});
  await page.route('**/api/v1/settings/credential-store',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({available:false,plaintext_fallback:false})}));
  await page.route('**/api/v1/settings/models',async route=>{await gate;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify([{id:'offline',protocol:'offline',base_url:'',models:['rules'],default_model:'rules',timeout_seconds:60,credential_ref:null,configured:true}])}).catch(()=>{});});
  await page.goto(`/#session=${session}`);
  await page.getByRole('button',{name:'模型设置',exact:true}).click();
  await page.getByRole('button',{name:'新增模型服务',exact:true}).click();
  await page.getByLabel('模型服务 ID').fill('late-catalog');
  await page.getByRole('button',{name:'保存模型配置',exact:true}).click();
  await expect(page.getByRole('status').filter({hasText:'模型配置已保存'})).toBeVisible();
  const response=page.waitForResponse(r=>r.url().endsWith('/api/v1/settings/models')&&r.request().method()==='GET');release();await response;
  await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));
  await expect(page.getByLabel('已配置模型服务')).toHaveValue('late-catalog');
  await expect(page.getByRole('button',{name:'连接测试（不推理）',exact:true})).toBeEnabled();
});

test('model-settings: discover, configure, share with CLI, and cancel without blocking data',async({page})=>{
  await page.goto(`/#session=${session}`);
  await expect(page.getByRole('button',{name:'模型设置',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'模型设置',exact:true}).click();
  await page.getByRole('button',{name:'新增模型服务',exact:true}).click();
  await page.getByLabel('模型服务 ID').fill('browser-lab');
  await page.getByLabel('模型协议').selectOption('openai-compatible');
  await page.getByLabel('服务地址').fill('http://127.0.0.1:8879/fake-model/v1');
  await page.getByLabel('凭据方式').selectOption('environment');
  await page.getByLabel('凭据环境变量').fill('CDAF_BROWSER_TEST_KEY');
  await page.getByLabel('默认模型 ID').fill('manual-model');
  await page.getByRole('button',{name:'保存模型配置',exact:true}).click();
  await expect(page.getByRole('status').filter({hasText:'模型配置已保存'})).toBeVisible();
  await page.getByRole('button',{name:'连接测试（不推理）',exact:true}).click();
  await expect(page.getByTestId('connection-result')).toContainText('connected');
  await page.getByLabel('搜索模型').fill('model-b');
  await expect(page.getByRole('option',{name:'model-b',exact:true})).toHaveCount(1);
  await page.screenshot({path:'../docs/assets/research-model-settings.png'});
  const info=await page.evaluate(async()=>{const token=sessionStorage.getItem('cdaf-session');return (await fetch('/api/v1/research/info',{headers:{Authorization:'Bearer '+token}})).json();});
  const output=execFileSync(process.platform==='win32'?'../.venv/Scripts/python.exe':'../.venv/bin/python',['-X','utf8','-m','contract_driven_ai_flow','models','list','--project',info.root],{encoding:'utf8'});
  expect(JSON.parse(output).find((p:{id:string})=>p.id==='browser-lab').default_model).toBe('manual-model');
  await page.getByLabel('默认模型 ID').fill('slow-model');
  await page.getByRole('button',{name:'保存模型配置',exact:true}).click();
  await page.getByRole('button',{name:'推理测试（发送测试文本）',exact:true}).click();
  await expect(page.getByRole('button',{name:'取消模型请求',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'关闭模型设置',exact:true}).click();
  await page.getByLabel('运行记录').selectOption({label:await page.getByLabel('运行记录').locator('option').filter({hasText:'Analysis · completed'}).last().textContent()||''});
  await chooseValue(page,'X999');
  await expect(page.getByTestId('current-variable')).toHaveText('X999');
  await page.getByRole('button',{name:'模型设置',exact:true}).click();
  await page.getByRole('button',{name:'取消模型请求',exact:true}).click();
  await expect(page.getByTestId('connection-result')).toContainText('cancelled');
});

test('model-settings: automatic evidence tools and slow harness stay independently cancellable',async({page})=>{
  await page.goto(`/#session=${session}`);
  await researchApi(page,'settings/models/browser-lab',{profile:{id:'browser-lab',protocol:'openai-compatible',base_url:'http://127.0.0.1:8879/fake-model/v1',default_model:'harness-model'}},'PUT');
  await chooseExample(page);await runCompute(page);
  await chooseValue(page,'Z');
  await page.getByRole('button',{name:'智能助手',exact:true}).click();await page.getByRole('button',{name:'任务设置'}).click();
  await page.getByLabel('任务模型服务').selectOption('browser-lab');await page.getByLabel('任务模型',{exact:true}).fill('harness-model');
  await expect(page.getByLabel('允许读取脱敏样例')).not.toBeChecked();
  await page.getByLabel('任务指令').fill('解读标准化定义。');await page.getByRole('button',{name:'执行智能任务'}).click();
  await expect(page.getByTestId('task-record').first().locator(':scope > strong')).toContainText('intelligence.explain');
  await expect(page.getByTestId('task-record').first().locator('strong > span')).toHaveText('completed');
  await page.getByRole('button',{name:'查看智能结果'}).first().click();
  await expect(page.locator('.wb-ai-answer')).toContainText('真实定义');await expect(page.locator('.wb-context-view')).toContainText('source.read');
  await page.screenshot({path:'../docs/assets/research-model-explanation.png'});
  await page.getByRole('button',{name:'智能助手',exact:true}).click();await page.getByRole('button',{name:'任务设置'}).click();
  await page.getByLabel('任务模型',{exact:true}).fill('slow-model');await page.getByLabel('任务指令').fill('慢请求期间继续查看数据。');
  await page.getByRole('button',{name:'执行智能任务'}).click();await expect(page.getByRole('button',{name:'取消任务'}).first()).toBeVisible();
  await chooseValue(page,'X');
  await expect(page.getByTestId('current-variable')).toHaveText('X');
  await page.getByRole('button',{name:'取消任务'}).first().click();await expect(page.getByTestId('task-record').first()).toContainText('cancelled');
});
