import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
test.use({baseURL:'http://127.0.0.1:8879'});

test('model-settings: discover, configure, share with CLI, and cancel without blocking data',async({page})=>{
  await page.goto('/#session=research-test-session');
  await expect(page.getByRole('button',{name:'模型设置',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'模型设置',exact:true}).click();
  await page.getByRole('button',{name:'新增模型服务',exact:true}).click();
  await page.getByLabel('模型服务 ID').fill('browser-lab');
  await page.getByLabel('模型协议').selectOption('openai-compatible');
  await page.getByLabel('服务地址').fill('http://127.0.0.1:8879/fake-model/v1');
  await page.getByLabel('凭据方式').selectOption('environment');
  await page.getByLabel('凭据环境变量').fill('CDAF_BROWSER_TEST_KEY');
  await page.getByLabel('默认模型 ID').fill('manual-model');
  await page.getByRole('button',{name:'保存模型配置',exact:true}).click();
  await expect(page.getByRole('status').filter({hasText:'模型配置已保存'})).toBeVisible();
  await page.getByRole('button',{name:'连接测试（不推理）',exact:true}).click();
  await expect(page.getByTestId('connection-result')).toContainText('connected');
  await page.getByLabel('搜索模型').fill('model-b');
  await expect(page.getByRole('option',{name:'model-b',exact:true})).toHaveCount(1);
  await page.screenshot({path:'../docs/assets/research-model-settings.png'});
  const info=await page.evaluate(async()=>{const token=sessionStorage.getItem('cdaf-session');return (await fetch('/api/v1/research/info',{headers:{Authorization:'Bearer '+token}})).json();});
  const output=execFileSync(process.platform==='win32'?'../.venv/Scripts/python.exe':'../.venv/bin/python',['-X','utf8','-m','contract_driven_ai_flow','models','list','--project',info.root],{encoding:'utf8'});
  expect(JSON.parse(output).find((p:{id:string})=>p.id==='browser-lab').default_model).toBe('manual-model');
  await page.getByLabel('默认模型 ID').fill('slow-model');
  await page.getByRole('button',{name:'保存模型配置',exact:true}).click();
  await page.getByRole('button',{name:'推理测试（发送测试文本）',exact:true}).click();
  await expect(page.getByRole('button',{name:'取消模型请求',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'关闭模型设置',exact:true}).click();
  await page.getByLabel('运行记录').selectOption({label:await page.getByLabel('运行记录').locator('option').filter({hasText:'Analysis · completed'}).last().textContent()||''});
  await page.getByRole('searchbox',{name:'搜索变量'}).fill('X999');
  await page.getByRole('button',{name:/^X999 ·/}).first().click();
  await expect(page.getByTestId('current-variable')).toHaveText('X999');
  await page.getByRole('button',{name:'模型设置',exact:true}).click();
  await page.getByRole('button',{name:'取消模型请求',exact:true}).click();
  await expect(page.getByTestId('connection-result')).toContainText('cancelled');
});

test('model-settings: evidence scope is explicit and model explanations remain cancellable',async({page})=>{
  await page.goto('/#session=research-test-session');
  await page.evaluate(async()=>{await fetch('/api/v1/settings/models/browser-lab',{method:'PUT',headers:{Authorization:'Bearer '+sessionStorage.getItem('cdaf-session'),'Content-Type':'application/json'},body:JSON.stringify({profile:{id:'browser-lab',protocol:'openai-compatible',base_url:'http://127.0.0.1:8879/fake-model/v1',default_model:'model-a',credential_ref:'env:CDAF_BROWSER_TEST_KEY'}})});});
  await page.getByText('示例、脚本参数与扩展适配器',{exact:true}).click();
  await page.getByLabel('示例选择').selectOption('analysis');
  await page.getByLabel('脚本参数').fill('');
  await page.getByRole('button',{name:'运行分析',exact:true}).click();
  await expect(page.getByTestId('run-status')).toHaveText('completed',{timeout:15000});
  await page.getByRole('searchbox',{name:'搜索变量'}).fill('Z');
  await page.getByRole('button',{name:/^Z ·/}).first().click();
  await page.getByText('自然语言解释与发送范围',{exact:true}).click();
  await expect(page.getByLabel('解释模型服务')).toBeVisible();
  await page.getByLabel('解释模型服务').selectOption('browser-lab');
  await page.getByLabel('解释模型 ID').fill('model-a');
  await expect(page.getByLabel('包含脱敏样例')).not.toBeChecked();
  await page.getByRole('button',{name:'查看解释发送内容',exact:true}).click();
  await expect(page.getByTestId('explanation-context')).toContainText('Z = (X - mu) / sigma');
  await expect(page.getByTestId('explanation-context')).not.toContainText('"sample"');
  await page.getByRole('button',{name:'生成模型解释',exact:true}).click();
  await expect(page.getByTestId('model-explanation')).toContainText('尚未人工验证');
  await expect(page.getByTestId('model-explanation')).toContainText('24');
  await page.screenshot({path:'../docs/assets/research-model-explanation.png'});
  await page.getByLabel('解释模型 ID').fill('slow-model');
  await page.getByRole('button',{name:'生成模型解释',exact:true}).click();
  await expect(page.getByRole('button',{name:'取消解释请求',exact:true})).toBeVisible();
  await page.getByRole('img',{name:'矩阵热图'}).click({position:{x:12,y:12}});
  await page.getByRole('button',{name:'取消解释请求',exact:true}).click();
  await expect(page.getByTestId('explanation-status')).toContainText('cancelled');
});
