import {session} from './session';
import {test,expect} from '@playwright/test';
import {mkdtempSync,writeFileSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';

test.use({baseURL:'http://127.0.0.1:8879'});

test('research-journey: own code, numerical failure, saved probe, explanation scope and offline report',async({page})=>{
  const root=mkdtempSync(join(tmpdir(),'cdaf-own-analysis-'));
  const script=join(root,'自己的分析.py');
  const code='import numpy as np\nimport pandas as pd\nX = np.arange(12, dtype=float).reshape(3,4)\nmu = X.mean(axis=0)\nZ = X - mu\nZ[1,2] = np.nan\nframe = pd.DataFrame({"value":[1,2],"email":["lab-sensitive@example.org","another@example.org"]})\n';
  writeFileSync(script,code,'utf8');
  await page.goto(`/#session=${session}`);
  await page.getByLabel('分析脚本').fill(script);
  await page.getByRole('button',{name:'打开代码',exact:true}).click();
  await expect(page.getByLabel('源码第 5 行',{exact:true})).toContainText('Z = X - mu');
  const previousRun=await page.getByLabel('运行记录').inputValue();
  await page.getByRole('button',{name:'运行分析',exact:true}).click();
  await expect(page.getByLabel('运行记录')).not.toHaveValue(previousRun);
  await expect(page.getByTestId('run-status')).toHaveText('completed',{timeout:20000});
  await expect(page.getByTestId('quality-status')).toHaveText('fail');
  await page.getByRole('searchbox',{name:'搜索变量'}).fill('Z');
  await page.getByRole('button',{name:/^Z ·/}).first().click();
  await expect(page.getByRole('img',{name:'矩阵热图'})).toBeVisible();
  await expect(page.getByTestId('source-selection')).toContainText('Z[1,2] = np.nan');
  await page.getByRole('button',{name:'添加探针',exact:true}).click();
  await page.getByLabel('探针种类').selectOption('finite');
  await page.getByRole('button',{name:'预演探针',exact:true}).click();
  await expect(page.getByTestId('probe-preview')).toContainText('fail');
  await page.getByRole('button',{name:'保存探针定义',exact:true}).click();
  await expect(page.getByRole('status').filter({hasText:'探针已保存'})).toBeVisible();
  await page.getByText('自然语言解释与发送范围',{exact:true}).click();
  await expect(page.getByLabel('包含脱敏样例')).not.toBeChecked();
  await page.getByRole('button',{name:'查看解释发送内容',exact:true}).click();
  await expect(page.getByTestId('explanation-context')).not.toContainText('lab-sensitive@example.org');
  await expect(page.getByTestId('explanation-context')).not.toContainText('"sample"');
  const download=page.waitForEvent('download');
  await page.getByRole('button',{name:'导出离线报告',exact:true}).click();
  const report=await download;const file=await report.path();
  const html=readFileSync(file!,'utf8');
  expect(html).toContain('Scientific Dataflow');
  expect(html).not.toContain('lab-sensitive@example.org');
  expect(html).not.toMatch(/<script[^>]+src=["']https?:/);
  expect(readFileSync(script,'utf8')).toBe(code);
  await page.screenshot({path:'../docs/assets/research-journey.png'});
});
