import {chooseValue,selectObject,runCompute,researchApi} from './scientific-helpers';
import {session} from './session';
import {test,expect} from '@playwright/test';
import {mkdtempSync,writeFileSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';

test.use({baseURL:'http://127.0.0.1:8879'});

test('research-journey: own code, numerical failure, saved probe, explanation scope and offline report',async({page})=>{
  const root=mkdtempSync(join(tmpdir(),'cdaf-own-analysis-'));
  const script=join(root,'自己的分析.py');
  const code='import numpy as np\nimport pandas as pd\nX = np.arange(12, dtype=float).reshape(3,4)\nmu = X.mean(axis=0)\nZ = X - mu\nZ[1,2] = np.nan\nframe = pd.DataFrame({"value":[1,2],"email":["lab-sensitive@example.org","another@example.org"]})\n';
  writeFileSync(script,code,'utf8');
  await page.goto(`/#session=${session}`);
  await page.getByRole('button',{name:'打开源码配置'}).click();
  await page.getByLabel('分析脚本').fill(script);
  await page.getByRole('button',{name:'导入解析',exact:true}).click();
  await expect(page.getByLabel('源码第 5 行',{exact:true})).toContainText('Z = X - mu');
  await page.getByRole('button',{name:'打开源码配置'}).click();
  await runCompute(page);
  await expect(page.getByTestId('run-status')).toHaveText('completed',{timeout:20000});
  await chooseValue(page,'Z');
  await expect(page.getByTestId('probe-output').filter({hasText:'fail'}).first()).toBeVisible();
  await chooseValue(page,'Z');
  await expect(page.getByRole('img',{name:'矩阵热图'})).toBeVisible();
  await expect(page.getByTestId('source-selection')).toContainText('Z[1,2] = np.nan');
  await page.getByRole('button',{name:'探针台',exact:true}).click();
  await page.getByRole('button',{name:'添加探针',exact:true}).click();await page.getByLabel('探针类型').selectOption('check.finite');
  await page.getByRole('button',{name:'确认添加探针'}).click();await page.getByRole('button',{name:'保存',exact:true}).click();
  const configuration=await researchApi(page,'research/workbench/configuration');expect(configuration.probes.some((p:{definition_id:string})=>p.definition_id==='check.finite')).toBe(true);
  await page.getByRole('button',{name:'智能助手',exact:true}).click();await page.getByRole('button',{name:'任务设置'}).click();
  await expect(page.getByLabel('允许读取脱敏样例')).not.toBeChecked();
  const download=page.waitForEvent('download');
  await page.getByRole('button',{name:'导出报告',exact:true}).click();
  const report=await download;const file=await report.path();
  const html=readFileSync(file!,'utf8');
  expect(html).toContain('Scientific Dataflow');
  expect(html).not.toContain('lab-sensitive@example.org');
  expect(html).not.toMatch(/<script[^>]+src=["']https?:/);
  expect(readFileSync(script,'utf8')).toBe(code);
  await page.screenshot({path:'../docs/assets/research-journey.png'});
});
