import { test, expect } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';

test('real graph, history, probes, theme and offline export', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/#session=browser-test-session');
  await expect(page.getByRole('heading', { name: 'Design with clear boundaries.' })).toBeVisible();
  await expect(page.locator('.react-flow__node')).toHaveCount(4);
  await page.getByRole('tab', { name: 'Runs', exact: true }).click();
  await expect(page.getByText('Quality failed', { exact: true })).toBeVisible();
  await expect(page.locator('.timeline-rows button')).toHaveCount(4);
  await page.getByRole('button', { name: 'Fit graph', exact: true }).click();
  await mkdir('../docs/assets', { recursive: true });
  await page.screenshot({ path: '../docs/assets/studio-runtime.png', fullPage: true });
  await page.getByRole('tab', { name: 'Probes', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Preview rule', exact: true })).toBeVisible();
  await page.getByLabel('Probe expression', { exact: true }).fill('$output.mean <= 5');
  await page.getByLabel('Preview sample', { exact: true }).fill('{"mean": 20, "count": 3}');
  await page.getByRole('button', { name: 'Preview rule', exact: true }).click();
  await expect(page.locator('.preview-result')).toContainText('"status": "fail"');
  await page.getByLabel('Probe kind', { exact: true }).selectOption('capture');
  await page.getByLabel('Probe data pointer', { exact: true }).fill('/password');
  await page.getByLabel('Preview sample', { exact: true }).fill('{"password": 7382941}');
  await page.getByRole('button', { name: 'Preview rule', exact: true }).click();
  await expect(page.locator('.preview-result')).toContainText('[REDACTED]');
  await expect(page.locator('.preview-result')).not.toContainText('7382941');
  await page.getByRole('button', { name: 'Toggle theme' }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  const downloaded = page.waitForEvent('download');
  await page.getByLabel('Export format').selectOption('html');
  const artifact = await downloaded; const filename = '../.work/browser-offline.html'; await artifact.saveAs(filename);
  await page.goto('file:///' + process.cwd().replaceAll('\\', '/') + '/' + filename);
  await expect(page.locator('[data-node]')).toHaveCount(4);
  await page.getByLabel('Search modules').fill('summarize');
  await expect(page.locator('[data-node].dim')).toHaveCount(3);
  expect(errors).toEqual([]);
});

test('canvas contract edit, review and real rerun share one revision', async ({ page }) => {
  await page.goto('/#session=browser-test-session');
  await expect(page.locator('.react-flow__node')).toHaveCount(4);
  await page.getByRole('button', { name: 'Validate', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Compilation passed');
  await page.getByRole('button', { name: 'Contract', exact: true }).click();
  const contract = JSON.parse(await page.getByLabel('Module contract JSON').inputValue());
  contract.examples.push({ input: { values: [2, 4] }, output: { mean: 3, count: 2 } });
  await page.getByLabel('Module contract JSON').fill(JSON.stringify(contract, null, 2));
  await page.getByRole('button', { name: 'Update draft contract' }).click();
  await expect(page.getByText('UNREVIEWED DRAFT', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Review & save', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Accept reviewed change' })).toBeVisible();
  await page.getByRole('button', { name: 'Accept reviewed change' }).click();
  await expect(page.getByRole('status')).toContainText('Accepted');
  await page.getByRole('tab', { name: 'Probes', exact: true }).click();
  await expect(page.locator('.module-node .quality-label')).toHaveCount(0);
  await page.getByRole('tab', { name: 'Architecture', exact: true }).click();
  const current = await (await page.request.get('/api/v1/project', { headers: { Authorization: 'Bearer browser-test-session' } })).json();
  const downloading = page.waitForEvent('download');
  await page.getByLabel('Export format', { exact: true }).selectOption('json');
  const exported = await downloading;
  const exportFile = '../.work/browser-current.json'; await exported.saveAs(exportFile);
  const { readFile } = await import('node:fs/promises');
  const document = JSON.parse(await readFile(exportFile, 'utf8'));
  expect(document.revision).toBe(current.revision); expect(document.run).toBeNull();
  await page.getByRole('tab', { name: 'Runs', exact: true }).click();
  await page.getByRole('button', { name: 'Overview', exact: true }).click();
  await page.getByRole('button', { name: 'Success fixture', exact: true }).click();
  await page.getByRole('button', { name: 'Run with this input', exact: true }).click();
  await expect(page.locator('.quality-pill')).toContainText('completed · quality passed', { timeout: 30000 });
  const screenshot = '../docs/assets/studio-architecture.png';
  await page.getByRole('tab', { name: 'Architecture', exact: true }).click();
  await page.screenshot({ path: screenshot, fullPage: true });
});

test('search latency is measured and keyboard selection works', async ({ page }) => {
  await page.goto('/#session=browser-test-session');
  await expect(page.locator('.react-flow__node')).toHaveCount(4);
  const started = Date.now();
  await page.getByLabel('Search modules').fill('summarize');
  await expect(page.locator('.module-node.dimmed')).toHaveCount(3);
  const latency = Date.now() - started;
  await page.getByLabel('Search modules').fill('');
  await page.locator('.react-flow__node').first().focus();
  await page.keyboard.press('Enter');
  await expect(page.locator('.react-flow__node').first()).toBeFocused();
  await writeFile('../docs/assets/browser-performance.json', JSON.stringify({ viewport: { width: 1600, height: 1000 }, nodes: 4, search_interaction_ms: latency, reduced_motion: true, measured_at: new Date().toISOString(), note: 'See docs/assets/large-graph-performance.json for the separate folded-graph measurement.' }, null, 2));
});

test('input binding can be edited and reviewed from the canvas', async ({ page }) => {
  await page.goto('/#session=browser-test-session');
  await expect(page.locator('.react-flow__node')).toHaveCount(4);
  await page.getByRole('button', { name: 'Normalize', exact: true }).click();
  await page.getByText('Bind module inputs', { exact: true }).click();
  await expect(page.getByLabel('Binding pointer for values', { exact: true })).toHaveValue('');
  await page.getByLabel('Visibility cap for values', { exact: true }).selectOption('L1');
  await page.getByRole('button', { name: 'Apply binding for values', exact: true }).click();
  await page.getByLabel('Source for scale', { exact: true }).selectOption('literal');
  await page.getByLabel('Literal value for scale', { exact: true }).fill('2');
  await page.getByRole('button', { name: 'Apply binding for scale', exact: true }).click();
  await page.getByRole('button', { name: 'Review & save', exact: true }).click();
  await expect(page.locator('.diff')).toContainText('literal');
  await page.getByRole('button', { name: 'Accept reviewed change', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Accepted');
  const context = await (await page.request.get('/api/v1/context/normalize?level=L4', { headers: { Authorization: 'Bearer browser-test-session' } })).json();
  expect(context.entries.find((entry: any) => entry.role === 'upstream').visibility).toBe('L1');
  expect(context.entries.find((entry: any) => entry.role === 'upstream').source).toBeUndefined();
});

test('new contract module, offline implementation review, execution and inverse rollback', async ({ page }) => {
  await page.goto('/#session=browser-test-session');
  await expect(page.locator('.react-flow__node')).toHaveCount(4);
  await page.getByRole('button', { name: 'New module', exact: true }).click();
  await page.getByLabel('Module identifier', { exact: true }).fill('hello_code');
  await page.getByLabel('New module contract', { exact: true }).fill(JSON.stringify({ input: { type: 'object', properties: {}, additionalProperties: false }, output: { type: 'string' }, examples: [{ input: {}, output: 'hello from contract' }] }));
  await page.getByRole('button', { name: 'Add to architecture draft', exact: true }).click();
  await page.getByRole('button', { name: 'Review & save', exact: true }).click();
  await page.getByRole('button', { name: 'Accept reviewed change', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Accepted');
  await page.getByRole('button', { name: 'Context', exact: true }).click();
  await page.getByRole('button', { name: 'Generate from offline fixtures', exact: true }).click();
  await expect(page.locator('.diff-pane .panel-heading strong')).toHaveText('mock implementation: hello_code');
  await expect(page.locator('.diff')).toContainText('hello from contract');
  await page.screenshot({ path: '../docs/assets/studio-review.png', fullPage: true });
  await page.getByRole('button', { name: 'Accept reviewed change', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Accepted');
  await page.getByRole('tab', { name: 'Runs', exact: true }).click();
  await page.getByRole('button', { name: 'Overview', exact: true }).click();
  await page.getByRole('button', { name: 'Success fixture', exact: true }).click();
  await page.getByRole('button', { name: 'Run with this input', exact: true }).click();
  await expect(page.locator('.quality-pill')).toContainText('completed · quality passed', { timeout: 30000 });
  await page.getByRole('tab', { name: 'Review', exact: true }).click();
  await page.getByRole('button', { name: 'Propose rollback', exact: true }).click();
  await expect(page.locator('.diff')).toContainText('NotImplementedError');
  await page.getByRole('button', { name: 'Accept reviewed change', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Accepted');
  await page.getByRole('tab', { name: 'Runs', exact: true }).click();
  await page.getByRole('button', { name: 'Run with this input', exact: true }).click();
  await expect(page.locator('.quality-pill')).toContainText('failed · quality unknown', { timeout: 30000 });
});

test('large folded graph, Chinese labels and background layout stay interactive', async ({ page }) => {
  const headers = { Authorization: 'Bearer browser-test-session' };
  const current = await (await page.request.get('/api/v1/project', { headers })).json();
  const template = current.project.modules[0];
  const contract = { input: { type: 'object', properties: {}, required: [], additionalProperties: false }, output: { type: 'object', properties: {}, required: [], additionalProperties: false }, examples: [] };
  const groups = Array.from({ length: 30 }, (_, i) => `group_${i}`);
  const modules = groups.flatMap((id, i) => [
    { ...template, id, name: `复合模块 ${i + 1}`, kind: 'composite', symbol: null, contract, outputs: {}, parent: null },
    ...Array.from({ length: 20 }, (_, j) => ({ ...template, id: `${id}_step_${j}`, name: `数据处理 ${i + 1} / ${j + 1}`, parent: id, contract })),
  ]);
  const project = { ...current.project, name: 'Large code structure · 大型折叠图', modules, bindings: [], probes: [], metadata: {} };
  const proposal = await page.request.post('/api/v1/changes/architecture', { headers, data: { project, base_revision: current.revision } });
  expect(proposal.ok()).toBeTruthy();
  const change = await proposal.json(); expect(change.status).toBe('proposed');
  expect((await page.request.post(`/api/v1/changes/${change.id}/accept`, { headers, data: { base_revision: current.revision } })).ok()).toBeTruthy();
  await page.request.put('/api/v1/view', { headers, data: { view: { positions: {}, collapsed: groups, theme: 'dark' }, base_revision: current.view.revision } });
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  const foldedStarted = Date.now(); await page.goto('/#session=browser-test-session');
  await expect(page.locator('.react-flow__node')).toHaveCount(30, { timeout: 30000 });
  const foldedMs = Date.now() - foldedStarted;
  await expect(page.locator('.node-name').first()).toContainText('复合模块');
  const interactionStarted = Date.now();
  await page.keyboard.press('Control+k'); await expect(page.getByLabel('Search modules')).toBeFocused();
  await page.getByLabel('Search modules').fill('复合模块 1');
  await expect(page.locator('.module-node.dimmed')).toHaveCount(19);
  const searchMs = Date.now() - interactionStarted;
  await page.screenshot({ path: '../docs/assets/studio-large-folded.png', fullPage: true });
  const view = await (await page.request.get('/api/v1/project', { headers })).json();
  await page.request.put('/api/v1/view', { headers, data: { view: { positions: {}, collapsed: [], theme: 'dark' }, base_revision: view.view.revision } });
  const expandedStarted = Date.now(); await page.reload();
  await expect(page.locator('.react-flow__node')).toHaveCount(630, { timeout: 40000 });
  const expandedMs = Date.now() - expandedStarted;
  const elapsed = await page.locator('.statusbar').innerText();
  expect(errors).toEqual([]);
  await writeFile('../docs/assets/large-graph-performance.json', JSON.stringify({ total_modules: 630, composite_groups: 30, folded_visible_nodes: 30, folded_load_and_layout_ms: foldedMs, expanded_load_and_layout_ms: expandedMs, search_interaction_ms: searchMs, expanded_footer: elapsed, browser: 'Playwright', reduced_motion: true, measured_at: new Date().toISOString() }, null, 2));
});
