import { useCallback, useEffect, useState } from 'react';
import { api, download, projectPrefix } from './api';
import { Tabs } from './components';

const json = (value: unknown) => JSON.stringify(value, null, 2);

function Result({ value }: { value: unknown }) { return value === null ? null : <pre className="tool-result" role="status">{json(value)}</pre>; }

export function FeatureReference({ features }: { features: any[] }) {
  const [search, setSearch] = useState('');
  return <section className="feature-reference"><h2>Web and CLI command reference</h2><p>The same project definitions, revisions and services drive both interfaces. Global <code>--json</code> gives machine-readable output; <code>--human</code> gives readable output. Use <code>-h</code> or <code>--help</code> on any command.</p><label className="field"><span>Find a feature</span><input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Probe, export, migrate…" /></label><div className="feature-list">{features.filter(feature => json(feature).toLowerCase().includes(search.toLowerCase())).map(feature => <article key={feature.id}><h3>{feature.name}</h3><p>{feature.description}</p><small>Web: {feature.web}</small><code>{feature.cli}</code></article>)}</div><p>Compatibility: <code>sfa</code> opens the current CLI; <code>sfa legacy --help</code> exposes legacy commands. Use Migration to bring legacy definitions into this editor.</p></section>;
}

export function Installation({ workspace = false }: { workspace?: boolean }) {
  const [diagnosis, setDiagnosis] = useState<any>(null); const [directory, setDirectory] = useState(''); const [result, setResult] = useState<any>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const check = useCallback(async () => { try { setDiagnosis(await api('/doctor', 'GET', undefined, workspace)); } catch (err) { setError((err as Error).message); } }, [workspace]);
  useEffect(() => { void check(); }, [check]);
  return <section className="tool-section"><h2>Installation and local launch</h2><p>Use <code>cdaf studio</code> to open the application. Closing the last connected tab stops its owned service after the refresh grace period. <code>cdaf serve</code> keeps a service running independently; <code>cdaf studio --stop</code> stops it explicitly.</p><button onClick={() => void check()}>Check installation</button>{diagnosis && <><ul className="diagnostic-list">{diagnosis.checks.map((check: any) => <li key={check.name}><strong>{check.name}</strong><span className={'quality-pill ' + check.status}>{check.status}</span><p>{check.detail}</p>{check.status !== 'passed' && <p>{check.remedy}</p>}</li>)}</ul><p>Version {diagnosis.version} · <code>{diagnosis.python}</code></p><h3>Legacy generation providers</h3><ul>{diagnosis.providers.map((provider: any) => <li key={provider.id}>{provider.name}: {provider.installed ? 'adapter installed' : 'install the [ai] extra'}; {provider.configured ? 'configured' : 'environment credential missing'}{provider.credential_environment && <code> {provider.credential_environment}</code>}</li>)}</ul><p className="muted">Scientific explanations use Model Settings in the research workbench. The legacy generation adapter uses explicitly configured server environment references; this screen never displays key values.</p></>}
    <h3>Single launch shortcut</h3><p>Create one shortcut for this installed Python environment. Opening it starts the workbench; closing the last connected tab stops its owned service. Windows uses a native .lnk file; macOS uses a .command launcher; Linux uses a .desktop entry.</p><label className="field"><span>Shortcut directory (optional; Desktop by default)</span><input value={directory} onChange={event => setDirectory(event.target.value)} placeholder="Leave empty for Desktop" /></label><button disabled={busy} onClick={async () => { setBusy(true); setError(''); try { setResult(await api('/shortcuts', 'POST', { directory: directory || null }, workspace)); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }}>Create launch shortcut</button>{error && <p role="alert" className="error">{error}</p>}<Result value={result} />
  </section>;
}

export function Maintenance({ workspace = false, onChanged }: { workspace?: boolean; onChanged?: () => Promise<void> }) {
  const [source, setSource] = useState(''); const [destination, setDestination] = useState(''); const [resolutions, setResolutions] = useState('{}'); const [preview, setPreview] = useState<any>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const invalidate = () => setPreview(null);
  const migrate = async (apply: boolean) => { setBusy(true); setError(''); try { const result = await api('/migrate', 'POST', { source, destination: destination || null, resolutions: JSON.parse(resolutions), apply }, workspace); setPreview(result); if (apply) await onChanged?.(); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } };
  return <section className="tool-section"><h2>Preview legacy migration</h2><p>Read an existing SFA project, resolve ambiguous bindings, and create a separate project. The source directory is preserved; migration never overwrites an existing destination.</p><label className="field"><span>Legacy source directory</span><input value={source} onChange={event => { setSource(event.target.value); invalidate(); }} placeholder="Folder containing .sfa/pipeline.yml" /></label><label className="field"><span>Separate destination directory (optional)</span><input value={destination} onChange={event => { setDestination(event.target.value); invalidate(); }} placeholder="Defaults to source-name-cdaf beside the source" /></label><label className="field"><span>Binding resolutions JSON</span><textarea value={resolutions} rows={7} onChange={event => { setResolutions(event.target.value); invalidate(); }} spellCheck={false} /></label><div className="button-row"><button disabled={busy || !source} onClick={() => void migrate(false)}>Preview migration</button><button className="primary" disabled={busy || !preview || preview.applied || preview.issues.length > 0 || preview.diagnostics.some((item: any) => item.severity === 'error')} onClick={() => void migrate(true)}>Create migrated project</button></div>{error && <p role="alert" className="error">{error}</p>}<Result value={preview} />
  </section>;
}

function Storage({ refresh }: { refresh: () => Promise<void> }) {
  const [before, setBefore] = useState(''); const [result, setResult] = useState<any>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [armed, setArmed] = useState(false);
  const clean = async (runs_before: string | null) => { setBusy(true); setError(''); try { setResult(await api('/clean', 'POST', { runs_before })); await refresh(); setArmed(false); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } };
  return <section className="tool-section"><h2>Storage maintenance</h2><p>Cache can be regenerated. Project definitions, contracts, probes, source files and views are preserved by these operations.</p><button disabled={busy} onClick={() => void clean(null)}>Clear generated cache</button><h3>Remove old completed runs</h3><p>This permanently removes completed run records and their events before the selected timestamp. Queued, running and paused runs are preserved. Export any evidence you want to keep first.</p><label className="field"><span>Before ISO timestamp</span><input value={before} onChange={event => { setBefore(event.target.value); setArmed(false); }} placeholder="2026-01-01T00:00:00+00:00" /></label>{armed ? <div className="button-row"><button onClick={() => setArmed(false)}>Keep records</button><button className="danger" disabled={busy} onClick={() => void clean(before)}>Remove completed runs before this timestamp</button></div> : <button disabled={!before || busy} onClick={() => setArmed(true)}>Review cleanup scope</button>}{error && <p role="alert" className="error">{error}</p>}<Result value={result} /></section>;
}

export function ProjectTools({ project, revision, refresh, onProposal }: { project: any; revision: string; refresh: () => Promise<void>; onProposal: (proposal: any) => Promise<void> }) {
  const [tab, setTab] = useState('Plan & sources'); const [result, setResult] = useState<any>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [sourceDir, setSourceDir] = useState('src'); const [spec, setSpec] = useState(json(project)); const [features, setFeatures] = useState<any[]>([]);
  const [format, setFormat] = useState('otel'); const [archify, setArchify] = useState(''); const [runId, setRunId] = useState(''); const [runs, setRuns] = useState<any[]>([]);
  const act = async (fn: () => Promise<void>) => { setError(''); setBusy(true); try { await fn(); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } };
  useEffect(() => { void api('/capabilities').then(data => setFeatures(data.features)).catch(err => setError(err.message)); void api('/runs').then(setRuns).catch(err => setError(err.message)); }, []);
  const tabs = ['Plan & sources', 'Import proposal', 'Integrations', 'Migration', 'Storage', 'Installation', 'Command reference'];
  return <div className="project-tools"><div className="tool-navigation"><Tabs items={tabs} value={tab} onChange={(value: string) => { setTab(value); setResult(null); setError(''); }} label="Project tool sections" prefix="tools" /></div><section className="tool-content" id="tools-panel" role="tabpanel" aria-labelledby={`tools-${tabs.indexOf(tab)}`}>
    {error && <p role="alert" className="notice error">{error}</p>}
    {tab === 'Plan & sources' && <section className="tool-section"><h2>Inspect the execution structure</h2><p>Compilation expands composite public interfaces and explicit bindings into the executable graph. Inspect it without running Python code.</p><button disabled={busy} onClick={() => void act(async () => setResult(await api('/plan')))}>Show execution plan</button><h3>Scan Python candidates</h3><label className="field"><span>Source directory within the project</span><input value={sourceDir} onChange={event => setSourceDir(event.target.value)} /></label><button disabled={busy} onClick={() => void act(async () => setResult(await api('/candidates?source_dir=' + encodeURIComponent(sourceDir))))}>Scan source symbols</button><p className="muted">Candidates do not change topology. Use New module / Import to choose a symbol and define its contract.</p><Result value={result} /></section>}
    {tab === 'Import proposal' && <section className="tool-section"><h2>Review an architecture proposal</h2><p>Paste or load a versioned ProjectSpec from an external agent or an exported model. The compiler validates it, then Review displays the difference before acceptance.</p><label className="field"><span>Architecture proposal JSON</span><textarea rows={20} spellCheck={false} value={spec} onChange={event => setSpec(event.target.value)} /></label><label className="field"><span>Load JSON file</span><input type="file" accept="application/json,.json" onChange={event => { const file = event.target.files?.[0]; if (file) void file.text().then(setSpec); }} /></label><button className="primary" disabled={busy} onClick={() => void act(async () => { const proposal = await api('/changes/architecture', 'POST', { project: JSON.parse(spec), base_revision: revision, title: 'Imported architecture proposal' }); await onProposal(proposal); })}>Validate &amp; review proposal</button></section>}
    {tab === 'Integrations' && <section className="tool-section"><h2>Integration exports</h2><p>Export local sanitized evidence for OpenTelemetry, or a graph for the optional pinned Archify viewer. These files do not send data to a remote collector.</p><label className="field"><span>Integration format</span><select value={format} onChange={event => setFormat(event.target.value)}><option value="otel">OpenTelemetry JSON</option><option value="archify-json">Archify graph JSON</option><option value="archify">Archify standalone HTML</option></select></label>{format === 'otel' && <label className="field"><span>Recorded run</span><select value={runId} onChange={event => setRunId(event.target.value)}><option value="">Latest recorded run</option>{runs.map(run => <option key={run.id} value={run.id}>{run.id.slice(0, 8)} · {run.status} / {run.quality}</option>)}</select></label>}{format === 'archify' && <label className="field"><span>Pinned Archify checkout</span><input value={archify} onChange={event => setArchify(event.target.value)} placeholder="Local tt-a1i/archify at a07fa1d" /></label>}<button disabled={busy || format === 'archify' && !archify} onClick={() => void act(async () => { await download(format, format === 'otel' ? runId || undefined : undefined, archify || undefined); setResult({ exported: format, sanitized: true }); })}>Download integration export</button><p className="muted">The core editor and runtime work independently of Archify. Other export formats are available in the main Export menu.</p></section>}
    {tab === 'Migration' && <Maintenance />}{tab === 'Storage' && <Storage refresh={refresh} />}{tab === 'Installation' && <Installation />}{tab === 'Command reference' && <FeatureReference features={features} />}
    {projectPrefix && <a className="back-workspace" href="/">Back to all projects</a>}
  </section></div>;
}
